/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule CategoryMenuQuery.graphql
 * @generated SignedSource<<d2e5f76004b514c7626e540bd3d82b6d>>
 * @relayHash e7cd9940d75a639d965b70e2855bfa3e
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query CategoryMenuQuery {
  categories {
    id
    label
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "CategoryMenuQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Category",
        "name": "categories",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "label",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "CategoryMenuQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "CategoryMenuQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Category",
        "name": "categories",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "label",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query CategoryMenuQuery {\n  categories {\n    id\n    label\n  }\n}\n"
};

module.exports = batch;
